### ISSUE TITLE
录制文件播放时的时长问题

### ISSUE THREAD

**Issue by ruidoc** [Monibuca/plugin-record#22]
M7S开启录制生成 .flv 文件，在使用 Flv.js 播放时，获取录像的时长有问题，主要是 duration 有问题，有以下两种表现：

## 1. 无限时长

没有视频时长，像直播一样，duration = Infinity

![image](https://user-images.githubusercontent.com/16762714/229777040-e0a6765c-1937-4fab-a906-532ff09fd5f5.png)

## 2. 时长过长

一千多小时，肯定有问题，duration = 4295043.181

![image](https://user-images.githubusercontent.com/16762714/229778087-f8148b41-2494-4f34-9240-a58bf94f42af.png)

## m7s 配置

```
global:
  loglevel: debug # 日志级别，可选值：debug,info,warn,error,panic,fatal
  http:
    listenaddr: :8081 # 网关地址，用于访问API
    listenaddrtls: ""  # 用于HTTPS方式访问API的端口配置
    certfile: ""
    keyfile: ""
    cors: true  # 是否自动添加cors头
    username: ""  # 用户名和密码，用于API访问时的基本身份认证
    password: ""
  publish:
    pubaudio: true # 是否发布音频流
    pubvideo: true # 是否发布视频流
    kickexist: false # 剔出已经存在的发布者，用于顶替原有发布者
    publishtimeout: 10s # 发布流默认过期时间，超过该时间发布者没有恢复流将被删除
    delayclosetimeout: 0 # 自动关闭触发后延迟的时间(期间内如果有新的订阅则取消触发关闭)，0为关闭该功能，保持连接。
    waitclosetimeout: 15s # 发布者断开后等待时间，超过该时间发布者没有恢复流将被删除，0为关闭该功能，由订阅者决定是否删除
    buffertime: 0 # 缓存时间，用于时光回溯，0为关闭缓存
record:
  subscribe:
    subaudio: true # 是否订阅音频流
    subvideo: true # 是否订阅视频流
    subaudioargname: ats # 订阅音频轨道参数名
    subvideoargname: vts # 订阅视频轨道参数名
    subdataargname: dts # 订阅数据轨道参数名
    subaudiotracks: [] # 订阅音频轨道名称列表
    subvideotracks: [] # 订阅视频轨道名称列表
    submode: 0 # 订阅模式，0为跳帧追赶模式，1为不追赶（多用于录制），2为时光回溯模式
    iframeonly: false # 只订阅关键帧
    waittimeout: 10s # 等待发布者的超时时间，用于订阅尚未发布的流
  flv:
    ext: .flv
    path: /home/record/flv
    autorecord: true
    filter: ""
    fragment: 0
```
